In [17]:
import pandas as pd
df = pd.read_csv("Helsingin_pyorailijamaarat.csv",sep=";")
df.tail()

,Päivämäärä,Auroransilta,Eteläesplanadi,Huopalahti (asema),Kaisaniemi/Eläintarhanlahti,Kaivokatu,Kulosaaren silta et.,Kulosaaren silta po.,Kuusisaarentie,"Käpylä, Pohjoisbaana",...,Munkkiniemen silta eteläpuoli,Munkkiniemi silta pohjoispuoli,Heperian puisto/Ooppera,Pitkäsilta itäpuoli,Pitkäsilta länsipuoli,Lauttasaaren silta pohjoispuoli,Ratapihantie,Viikintie,Baana,Unnamed: 21
37161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
states = ["United Kingdom","Finland","USA","Sweden","Germany","Russia"]
year = [0,1917,1776,1523,0,1992]
heads = ["","Niinistö","Trump","","Steinmeier","Putin"]
data = { "State":states, "Year of Independence":year, "President":heads}
df = pd.DataFrame(data)
df.set_index("State")
df.describe

<bound method NDFrame.describe of             State  Year of Independence   President
0  United Kingdom                     0
1         Finland                  1917    Niinistö
2             USA                  1776       Trump
3          Sweden                  1523
4         Germany                     0  Steinmeier
5          Russia                  1992       Putin>